### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by sevstels** [skandhurkat/Getopt-for-Visual-Studio#2]
File: Getopt-for-Visual-Studio/getopt.h
# pragma warning(disable:4996); <- here need remove ;

**Comment by Globik** [comment]
Why?

**Comment by sevstels** [comment]
Because MVS pragma directive is macro expansion and not require ';'
https://msdn.microsoft.com/en-us/library/aa273917(v=vs.60).aspx

**Comment by sgeto** [comment]
good point 👍 
it's a preprocessor directive it doesn't need a semicolon at the end...

**Comment by skandhurkat** [comment]
Won't fix, use [vcpkg](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019) instead.
