### ISSUE TITLE
Won't compile in visual studio 2017

### ISSUE THREAD

**Issue by pkarpi** [skandhurkat/Getopt-for-Visual-Studio#4]
Error (active)	E0144	a value of type "const char *" cannot be used to initialize an entity of type "char *"

Line 125

**Comment by donRumata03** [comment]
I totally agree.
Fortunately, it works properly with const_cast<char*>(EMSG)

**Comment by plolcott** [comment]
The above solution must be applied several different places. 
Replacing line 115 with line 113 fixes the whole problem. 
#ifdef __CYGWIN__
static char EMSG[] = "";
#else
static char EMSG[] = "";
#endif

**Comment by skandhurkat** [comment]
[VCPKG](https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019) has a better port that guarantees compatibility. Therefore, this hacked up port from MinGW is deprecated.
